#!/usr/bin/env python3

# Simple script to get sustaining members and 
# other feeds and update our web site with them
# (c) Tim Sutton, 2023

import requests
import argparse
import json
import shutil
import os
from dateutil.parser import parse as date_parse
try:
    import urlparse
except ImportError:
    from urllib.parse import urlparse
from scripts.resize_image import resize_image

# (connect, read) timeouts in seconds so a hung host can't stall the job.
REQUEST_TIMEOUT = (10, 300)

### Funders
def fetch_funders(url: str):
    """
    Fetch the sustaining members from the QGIS changelog
    and create markdown files
    """
    response = requests.get(url, timeout=REQUEST_TIMEOUT)
    data = json.loads(response.text)
    items = data["rss"]["channel"]["item"]
    # The feed serialises a single member as a dict rather than a one-element
    # list, so normalise to a list before iterating to avoid walking dict keys.
    if isinstance(items, dict):
        items = [items]
    for item in items:
        member_slug = item["slug"]
        markdown_filename = f"content/funders/{member_slug}.md"
        link = item["member_url"]
        image_url = item["image_url"]
        title = item["title"]
        level = item["member_level"]
        country = item["member_country"]
        start_date = item["start_date"]
        end_date = item["end_date"]

        start_date = date_parse(start_date, fuzzy_with_tokens=True)[0]
        start_date = start_date.strftime("%Y-%m-%d")
        end_date = date_parse(end_date, fuzzy_with_tokens=True)[0]
        end_date = end_date.strftime("%Y-%m-%d")

        path = urlparse(image_url).path
        image_ext = os.path.splitext(path)[1]
        image_name = "%s.%s" % (member_slug, image_ext)
        image_name = image_name.replace("..",".")

        content = f"""---
# ⚠️  AUTOMATED FILE - DO NOT EDIT MANUALLY!
# Generated by: fetch_feeds.py
# Source: QGIS sustaining members API
# To update: Run 'fetch_feeds.py' (automated nightly via GitHub Actions)
# See CONTRIBUTING.md section: Automated Content and Manual Edit Guidelines

level: "{level}"
title: "{title}"
logo: "{image_name}"
startDate: "{start_date}"
endDate: "{end_date}"
link: "{link}"
country: "{country}"
---
"""
        with open(markdown_filename , "w", encoding="utf=8") as f:
            f.write(content)
            print(f"Writing: {markdown_filename}")

        response = requests.get(image_url, stream=True, timeout=REQUEST_TIMEOUT)
        image_filename = f"content/funders/{image_name}"
        with open(image_filename, 'wb') as out_file:
            shutil.copyfileobj(response.raw, out_file)
            print(f"Writing: {image_filename}")
        del response
        try:
            if level.lower() in ["flagship", "large"]:
                resize_image(image_filename, max_height=150)
            else:
                resize_image(image_filename)
        except Exception as e:
            print(f"Error resizing image: {e}")

def fetch_first_feed_entry():
    """
    Fetch the first entry from the QGIS feed and save it to data/feed.json
    """
    feed_url = "https://feed.qgis.org/?lang=en&json=1"
    feed_file_path = "data/feed.json"
    response = requests.get(feed_url, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()
    feed_data = response.json()
    entry = {}
    if feed_data and len(feed_data) > 0:
        entry = feed_data[0]
        entry['url'] = f"https://feed.qgis.org/{entry['pk']}"
        print(f"First feed entry saved to {feed_file_path}")
    os.makedirs(os.path.dirname(feed_file_path), exist_ok=True)
    with open(feed_file_path, "w", encoding="utf-8") as f:
        json.dump(entry, f, ensure_ascii=False, indent=4)


def main():
    argparse.ArgumentParser(description='Import items from various feeds.').parse_args()

    try:
        fetch_funders("https://members.qgis.org/en/members/json/")
    except Exception as e:
        print(f"Error fetching funders: {e}")

    try:
        # QGIS feed
        fetch_first_feed_entry()
    except Exception as e:
        print(f"Error fetching feed: {e}. Keeping the previous feed.json if it exists.")


if __name__ == "__main__":
    main()