import { test, expect } from '@playwright/test';

let url = '/';

test('home page', async ({ page }) => {
  await page.goto(url);
  await expect(page.getByRole('banner')).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link').first()).toBeVisible();
  await expect(page.getByLabel('main navigation').getByText('Product')).toBeVisible();
  await page.getByLabel('main navigation').getByText('Product').hover();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Overview' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Case studies' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Plugins' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Visual Changelogs' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByText('Community')).toBeVisible();
  await page.getByLabel('main navigation').getByText('Community').hover();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Get involved' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Become a Certified Member' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'QGIS Foundation' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Project Organisation' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Members Blog' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Download' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByText('Resources', { exact: true })).toBeVisible();
  await page.getByLabel('main navigation').getByText('Resources', { exact: true }).hover();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'QGIS Resources' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Installation Guide' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Documentation' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Releases' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Roadmap' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Reports' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Books' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Support' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Blog' })).toBeVisible();
  await expect(page.getByLabel('main navigation').getByRole('link', { name: 'Donate' })).toBeVisible();
  await expect(page.getByPlaceholder('Search')).toBeVisible();
  await expect(page.getByPlaceholder('Search')).toBeEmpty();
  await expect(page.locator('div').filter({ hasText: 'Free and open source Spatial' }).first()).toBeVisible();
  await expect(page.getByText('Free and open source').first()).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Spatial without compromise' })).toBeVisible();
  await expect(page.getByText('Giving the power of spatial')).toBeVisible();
  await expect(page.locator('section').filter({ hasText: 'Free and open source Spatial' }).getByRole('link')).toBeVisible();
  await expect(page.getByText('Available on Windows, Mac,')).toBeVisible();
  await expect(page.locator('section').filter({ hasText: 'Free and open source Spatial' }).getByRole('img')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Create maps' })).toBeVisible();
  await expect(page.getByText('Explore QGIS\'s exceptional')).toBeVisible();
  await expect(page.getByText('Class-leading cartography')).toBeVisible();
  await expect(page.getByText('Experience QGIS\' extensive')).toBeVisible();
  await expect(page.getByText('Professional map production')).toBeVisible();
  await expect(page.getByText('Use the intuitive layout')).toBeVisible();
  await expect(page.getByText('Powerful reporting tools')).toBeVisible();
  await expect(page.getByText('Create atlasses and reports')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Edit layers' })).toBeVisible();
  await expect(page.getByText('Harness the unmatched')).toBeVisible();
  await expect(page.locator('.deco-block-2 > img')).toBeVisible();
  await expect(page.locator('.deco-block-1 > img')).toBeVisible();
  await expect(page.getByText('Exceptional digitizing')).toBeVisible();
  await expect(page.getByText('Craft and edit points, lines')).toBeVisible();
  await expect(page.getByText('Advanced construction tools')).toBeVisible();
  await expect(page.getByText('Build geometries with curves')).toBeVisible();
  await expect(page.getByText('Highly customizable forms')).toBeVisible();
  await expect(page.getByText('Create user-friendly forms')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Process and analyze' })).toBeVisible();
  await expect(page.getByText('Benefit from state-of-the art')).toBeVisible();
  await expect(page.locator('.deco-block-3 > img')).toBeVisible();
  await expect(page.getByText('Comprehensive analysis toolset')).toBeVisible();
  await expect(page.getByText('Uncover insights from your')).toBeVisible();
  await expect(page.getByText('Automated analysis workflows')).toBeVisible();
  await expect(page.getByText('Visually combine analysis')).toBeVisible();
  await expect(page.getByText('Extensible analysis')).toBeVisible();
  await expect(page.getByText('Explore a diverse ecosystem')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Share maps' })).toBeVisible();
  await expect(page.getByText('QGIS provides an equal')).toBeVisible();
  await expect(page.locator('.deco-block-4 > img')).toBeVisible();
  await expect(page.getByText('Industry-leading format')).toBeVisible();
  await expect(page.getByText('Conquer data integration')).toBeVisible();
  await expect(page.getByText('Standards and interoperability')).toBeVisible();
  await expect(page.getByText('Amplify your impact by')).toBeVisible();
  await expect(page.getByText('Publish your work')).toBeVisible();
  await expect(page.getByText('Extend QGIS to the cloud and')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Explore QGIS' })).toBeVisible();
  await page.locator('div').filter({ hasText: '👋 The power of open source' }).first().click();
  await expect(page.locator('.explore > .columns > div > figure > img')).toBeVisible();
  await expect(page.getByRole('heading', { name: '👋 The power of open source' })).toBeVisible();
  await expect(page.getByText('Our community development')).toBeVisible();
  await expect(page.getByText('Join our annual international')).toBeVisible();
  await expect(page.getByText('Find local user groups and')).toBeVisible();
  await expect(page.getByText('Learn how people around the')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Get involved' }).first()).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Free and open source' })).toBeVisible();
  await expect(page.getByText('QGIS is a public project')).toBeVisible();
  await expect(page.getByText('For that reason QGIS is Free')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Free download' })).toBeVisible();
  await expect(page.frameLocator('iframe[title="YouTube video player"]').locator('.ytp-cued-thumbnail-overlay-image')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Start using QGIS 🚀' })).toBeVisible();
  await expect(page.getByText('Quick-start tutorials')).toBeVisible();
  await expect(page.getByText('Live demos')).toBeVisible();
  await expect(page.getByText('Up-to-date documentation')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Go to materials' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'QGIS supporters' })).toBeVisible();
  await expect(page.locator('div').filter({ hasText: 'Add your logo here?' }).nth(2)).toBeVisible();
  await expect(page.locator('div').filter({ hasText: 'Golden partner' }).nth(2)).toBeVisible();
  await expect(page.locator('.supporters-grid > div:nth-child(3)').first()).toBeVisible();
  await expect(page.locator('.tile > .tile').first()).toBeVisible();
  await expect(page.getByRole('contentinfo')).toBeVisible();
  await expect(page.getByRole('img', { name: 'Logo' })).toBeVisible();
  await expect(page.getByRole('link', { name: '' })).toBeVisible();
  await expect(page.getByRole('link', { name: '' })).toBeVisible();
  await expect(page.getByRole('link', { name: '' })).toBeVisible();
  await expect(page.locator('div:nth-child(2) > div:nth-child(2) > a:nth-child(4)').first()).toBeVisible();
  await expect(page.getByRole('link', { name: '' })).toBeVisible();
  await expect(page.getByRole('link', { name: '' })).toBeVisible();
});
