import { test, expect } from '@playwright/test';

let url = '/';

test('product page', async ({ page }) => {
  await page.goto(url);
  await page.locator('section').filter({ hasText: 'Free and open source Spatial' }).getByRole('link').click();
  await page.locator('#sidebar').getByRole('link', { name: 'Product' }).click();
  await expect(page.getByText('Free and open source')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'QGIS overview' })).toBeVisible();
  await expect(page.getByText('Giving the power of spatial')).toBeVisible();
  await expect(page.locator('section').filter({ hasText: 'Free and open source QGIS' }).getByRole('link')).toBeVisible();
  await expect(page.getByText('Available on Windows, Mac,')).toBeVisible();
  await expect(page.getByText('Key features ¶ Create map')).toBeVisible();
  await expect(page.getByText('Create map')).toBeVisible();
  await expect(page.getByText('Edit layers')).toBeVisible();
  await expect(page.getByText('Process and analyze')).toBeVisible();
  await expect(page.getByText('Share maps')).toBeVisible();
  await expect(page.locator('#content-tab-1').getByRole('img', { name: 'Create map' })).toBeVisible();
  await expect(page.getByText('Class-leading cartography ¶ Experience QGIS’ extensive set of design options to')).toBeVisible();
  await expect(page.getByRole('img', { name: 'Create map' }).nth(1)).toBeVisible();
  await expect(page.getByText('Enhance the functionality of')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Go to plugins' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'International conference' })).toBeVisible();
  await expect(page.getByText('Connect with professionals,')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Community meetings' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Local user groups' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Local user groups and support' })).toBeVisible();
  await expect(page.getByText('Join a community of like-')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Local groups list' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Join the community' })).toBeVisible();
  await expect(page.getByText('QGIS Server ¶ Publish your')).toBeVisible();
  await expect(page.getByText('QGIS Desktop ¶ Create, edit,')).toBeVisible();
  await expect(page.getByText('QGIS Web Client ¶ Publish')).toBeVisible();
  await expect(page.getByText('QGIS on mobiles and tablets ¶ The QGIS experience does not stop on the desktop')).toBeVisible();
  await expect(page.getByText('Case Studies ¶ We gather')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Amurum forest reserve habitat' })).toBeVisible();
  await expect(page.getByText('Maps showcase ¶ QGIS users')).toBeVisible();
  await expect(page.getByText('Application screenshots ¶ Below are some screenshots from QGIS itself and a')).toBeVisible();
  await page.getByRole('link', { name: 'Maps', exact: true }).click();
  await expect(page.getByText('QGIS Maps ¶ Amazing maps')).toBeVisible();
  await expect(page.getByText('Amazing maps created using')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Screenshots' })).toBeVisible();
  await page.getByRole('link', { name: 'Screenshots' }).click();
  await expect(page.getByText('QGIS Screenshots ¶ Screenshots of QGIS in action')).toBeVisible();
  await expect(page.getByText('Screenshots of QGIS in action')).toBeVisible();
  await page.locator('#sidebar').getByRole('link', { name: 'Case studies' }).click();
  await expect(page.getByText('Case Studies ¶ Amurum forest')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Amurum forest reserve habitat' })).toBeVisible();
  await expect(page.locator('#sidebar').getByRole('link', { name: 'Plugins' })).toBeVisible();
  await page.locator('#sidebar').getByRole('link', { name: 'Visual Changelogs' }).click();
  await expect(page.getByText('Visual Changelogs ¶ Below you')).toBeVisible();
});