#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Fetches the QGIS Grant Programme blog posts from the RSS feed and
# creates individual Markdown files for each post in content/community/organisation/grants/.
# Existing files are overwritten on each run to reflect the latest source content.

import os
import requests
import defusedxml.ElementTree as ET
from dateutil.parser import parse as date_parse
from bs4 import BeautifulSoup
from urllib.parse import urlparse

FEED_URL = "http://blog.qgis.org/category/qgis-grant-programme/feed"
GRANTS_FOLDER = "content/community/organisation/grants"



def slug_from_url(url):
    """Derive a filesystem-safe slug from a blog post URL."""
    path = urlparse(url).path.rstrip("/")
    return os.path.basename(path)


def extract_description(raw_html):
    """Strip HTML and remove trailing 'Read more' from the RSS description."""
    soup = BeautifulSoup(raw_html, "html.parser")
    for a in soup.find_all("a", class_="read-more"):
        a.decompose()
    return " ".join(soup.get_text(separator=" ").split())


def fetch_grants():
    os.makedirs(GRANTS_FOLDER, exist_ok=True)

    response = requests.get(FEED_URL)
    response.raise_for_status()

    root = ET.fromstring(response.content)
    channel = root.find("channel")

    for item in channel.findall("item"):
        title = (item.findtext("title") or "").strip()
        link = (item.findtext("link") or "").strip()
        pub_date_str = (item.findtext("pubDate") or "").strip()
        creator = (item.findtext("{*}creator") or "").strip()
        description_html = (item.findtext("description") or "").strip()
        content_encoded = (item.findtext("{*}encoded") or "").strip()

        if not title or not link:
            continue

        try:
            pub_date = date_parse(pub_date_str).strftime("%Y-%m-%d")
        except Exception:
            pub_date = pub_date_str

        slug = slug_from_url(link)
        markdown_filename = os.path.join(GRANTS_FOLDER, f"{slug}.md")

        description = extract_description(description_html)
        escaped_title = title.replace('"', '\\"')
        escaped_description = description.replace('"', '\\"')

        md_content = (
            "---\n"
            "# \u26a0\ufe0f  AUTOMATED FILE - DO NOT EDIT MANUALLY!\n"
            "# Generated by: scripts/fetch_grants.py\n"
            f"# Source: {link}\n"
            "# To update: Run 'scripts/fetch_grants.py' (automated nightly via GitHub Actions)\n"
            "# See CONTRIBUTING.md section: Automated Content and Manual Edit Guidelines\n"
            "\n"
            f'title: "{escaped_title}"\n'
            f'date: "{pub_date}"\n'
            f'description: "{escaped_description}"\n'
            f'link: "{link}"\n'
            f'author: "{creator}"\n'
            "draft: false\n"
            "HasBanner: false\n"
            "sidebar: true\n"
            "---\n"
            "\n"
            "{{< content-start >}}\n"
            "\n"
            f"{content_encoded}\n"
            "\n"
            f'<p><a href="{link}" target="_blank" rel="noopener noreferrer">'
            "View original post on blog.qgis.org \u2197</a></p>\n"
            "\n"
            "{{< content-end >}}\n"
        )

        with open(markdown_filename, "w", encoding="utf-8") as f:
            f.write(md_content)
            print(f"Writing: {markdown_filename}")


if __name__ == "__main__":
    fetch_grants()
