name: Transifex coverage

on:
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  fetch-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS.txt

      - name: Fetch coverage from Transifex
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          python scripts/tx_fetch_coverage.py \
            --project qgis-website \
            --resources qgis-hugo-docs-md \
            --output data/tx_coverage.json

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain data/tx_coverage.json)" ]]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'github-actions@github.com'
            git add data/tx_coverage.json
            git commit -m "Update translation coverage [skip ci]"
            git push
          else
            echo "No coverage changes"
          fi


